<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description>Universal adds the movies on this page regularly. If an end user submits the receipt belonging to these movies title, an end user will get 1000 points per movie.</description>
   <name>Add New Movie to Receipt Upload Page</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>1724999e-ee69-4fd7-b263-aec9e864fe78</testSuiteGuid>
   <testCaseLink>
      <guid>786e5372-d9a5-43df-886c-c6d4184ce141</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Receipt Upload/TC-Add new movie on Upload Receipt Page</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f8121e7-ab21-486d-aa93-8f506109d553</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c45039b2-2a01-415e-af1d-71e546f164b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5ec7e09c-bb1b-48da-8801-b25b67a3a464</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>466aee77-cb04-41ff-8955-65e031207e6d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c20f6d9a-1c27-4364-9708-f03b470b26a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f399bb2-406d-4a1d-8ce0-ce5a4eeadbd3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>82c9772f-ef5f-4ece-82bf-b71b72bbb862</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67f5a71e-6e8b-4e83-815a-73c7163fa2c5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0860850f-48d2-4b9d-ae6c-3b1cc08184fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e5918cf-3318-474e-b198-130169aab1e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>372c22b1-ceb1-4f74-8f3e-992dd0b82fde</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0fc87d61-3269-474e-b58b-56628a1b443c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dec71a4-bf44-4b22-9002-c290a50a7cf0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e40dbe89-660e-4f58-9203-b749ff07ca24</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Receipt Upload/UploadReceipt</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37bc073b-945f-4fd4-ae0a-88e4283b1b5f</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
