<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EarnPoint</name>
   <tag></tag>
   <elementGuidId>307411f2-613f-4ada-abf9-eb5d6dfa933d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;togglebtn&quot;]/ul/div/li[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;togglebtn&quot;]/ul/div/li[5]/a</value>
   </webElementProperties>
</WebElementEntity>
