<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Header</name>
   <tag></tag>
   <elementGuidId>243c4376-efb1-4366-bb4b-43b03667d274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/app-root/app-header//nav/app-account-menu//ul[@class='account-button-logged']//img[@alt='UserLevel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/app-root/app-header//nav/app-account-menu//ul[@class='account-button-logged']//img[@alt='UserLevel']</value>
   </webElementProperties>
</WebElementEntity>
