<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp-Close</name>
   <tag></tag>
   <elementGuidId>1fa4af4f-ad42-467e-ade2-6762e2077f27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;mat-dialog-0&quot;]/app-dynamic-message-pop-up-modal/div/div[2]/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;mat-dialog-0&quot;]/app-dynamic-message-pop-up-modal/div/div[2]/mat-icon</value>
   </webElementProperties>
</WebElementEntity>
