<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Description</name>
   <tag></tag>
   <elementGuidId>43d79425-eb65-4369-bbb0-3e6df08df294</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//app-point-history/div/mat-table/mat-row[1]/mat-cell[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//app-point-history/div/mat-table/mat-row[1]/mat-cell[1]</value>
   </webElementProperties>
</WebElementEntity>
