<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Long_Description</name>
   <tag></tag>
   <elementGuidId>d1c8b1de-068d-451f-a912-0d6b8a6ddba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;earn-points-action-preview-page&quot;]/div/div[2]/div[2]/div[3]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;earn-points-action-preview-page&quot;]/div/div[2]/div[2]/div[3]/div/p</value>
   </webElementProperties>
</WebElementEntity>
