<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c9becd62-070b-437f-a192-9dde2cdef181</testSuiteGuid>
   <testCaseLink>
      <guid>76a27bdb-5fa2-4652-9128-87e9d59b20f1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Universal/Login/TC-1 Login with Moviestar</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d8dd4781-a3fe-4260-82a4-41bca3c2b732</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b8c01bd-d1ed-460a-9c28-857ab1a504d7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>15343862-bc42-4164-b3fa-d3482469903e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8a6ee636-d0e1-4a05-b84e-108b48a615d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Universal/Login/TC-3 Login with Director</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95fb0e14-5fef-4fda-bedb-a1303e9990d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84e6614f-5623-4567-87f3-08512a37a8b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3b24039-6a49-40f9-8110-915778615d85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Universal/Login/TC-2 Login with Screenwriter</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a1b99cef-9aa6-4138-a15f-091595ef2cf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0acab48c-8340-4dd2-864e-d2f33981b4ec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>253cb894-cb9e-411d-9bc4-435c2bff5e62</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Universal/Login/TC-4 Login with Extra</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>67b33b4f-2999-4ffd-8a70-765b60f1ca9c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8f43b2d-1f27-484a-a740-5e374e46ce70</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
