<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ToastMessage</name>
   <tag></tag>
   <elementGuidId>c8c09197-de8a-4552-a72d-87d4628627e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='toast-container']//div[@role='alertdialog']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='toast-container']//div[@role='alertdialog']</value>
   </webElementProperties>
</WebElementEntity>
