# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI with katalonn

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
     - name: Set up JDK 8
       uses: actions/setup-java@v2
       with:
         java-version: '8'
         distribution: 'temurin'
     - name: Checkout
       uses: actions/checkout@v2
     - name: Katalon Studio Github Action
       uses: katalon-studio/katalon-studio-github-action@v2
       with:
          version: '8.2.0'
    
          ks_api_key: '${{ secrets.SECRETS_API_KEY }}'
          projectPath: '${{ github.WORKSPACE }}'
          args: '-noSplash -retry=0 -testSuiteCollectionPath="Test Suites/Test collection 2"  -apiKey= ${{ secrets.SECRETS_API_KEY }}   --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true'
     
